### ISSUE TITLE
[Bug][Workspace detail] Cannot view list of newly added Dataspaces

### ISSUE THREAD

**Issue by thomas-vmogroup** [Smartspace-ai/smartspace-sdk#58]
**Test step:**
1. Login to Admin
2. Navigate to Workspaces list page
3. Add new workspace with template: Chat to file v1.0.0
4. On VectorSearch block, click on setting icon
5. Add some dataspaces to block
6. Observe dataspace list

**Expected result:**
6. Can view all newly added dataspaces (add scrollbars)

**Actual:**
6. Cannot view all newly added dataspaces

Video:https://github.com/user-attachments/assets/9ded7d21-9c8f-47d4-8cef-ae270017b18a

**Comment by Toby-Hayward** [comment]
This is the expected behavior. You need to add dataspaces to the workspace using the tab located at the top. This is because dataspaces are locked down based on whether the workspace has access to them. By default, the workspace has access to none. Once you have added a dataspace to a workspace it will then show when clicking to add dataspaces in the vector search block

**Comment by thomas-vmogroup** [comment]
@Toby-Hayward , I can't see the data space list I just added here. My suggestion is to add a scrollbar, ok?

![Image](https://github.com/user-attachments/assets/a004a96d-1273-4bb5-b7f1-afd79f255555)
